### ISSUE TITLE
No es posible descargar ficheros de gran tamaño

### ISSUE THREAD

**Issue by alvrogd** [alvrogd/gradox-scraper#4]
Dado que el _script_ simplemente tiene en cuenta el tiempo que lleva descargando un fichero, en lugar de valorar también el tamaño de este, la descarga de los ficheros de gran tamaño resultará fallida a ojos del _script_ (realmente, el fichero acabará descargándose, pero no se organizará).

Debería tenerse también en cuenta el tamaño de un fichero para evitar este tipo de problemas.

**Comment by alvrogd** [comment]
Solucionado en 4894090bbc7013433a619e98a9b9bb1707a61bef.

Los ficheros son descargados ahora mediante el módulo _requests_, eliminando la necesidad de comprobar periódicamente si un fichero se ha terminado descargar o no, y solucionando por lo tanto este problema.

**Comment by alvrogd** [comment]
```
Traceback (most recent call last): fichero: Prácticas CoGa 2015-16 resoltas_260317122149.zip (17 de 22)
  File "./backup.py", line 197, in <module>
    retrieveSubjectContents(browser, s, subjectDirectory, subjectURL)
  File "./backup.py", line 143, in retrieveSubjectContents
    for chunk in data.iter_content(chunk_size=8192):
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.7/site-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.7/site-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2508)
```

**Comment by alvrogd** [comment]
El anterior error sucede descargando ficheros de gran tamaño (decenas de MB). Todavía desconozco el motivo.

**Comment by alvrogd** [comment]
https://stackoverflow.com/questions/21497591/urllib2-reading-https-url-failure

**Comment by alvrogd** [comment]
Empiezo a sospechar que el problema puede no ser del script, ya que he probado a descargar el fichero que daba problemas mediante Firefox y Chrome, y no han sido capaces de ello.

**Comment by alvrogd** [comment]
He probado el script bajo una máquina virtual con _Lubuntu 19.04_. Se han completado dos descargas desde cero del respositorio, sin ningún fallo.

De todos modos, también hubo una tercera descarga en la que el error apareció, pero directamente con el primer fichero que se intentó descargar, que tiene un tamaño total de 17,6MB. Esto es extraño porque nunca se había dado el error con ficheros menores a 50MB.

Ante esta situación, tengo aún más dudas sobre cuál puede ser el origen de este fallo. Por otra parte, no creo que me resulte conveniente invertir más horas en investigarlo porque tengo otras tareas que realizar que son más prioritarias.

Dejo el _issue_ abierto de forma indefinida, y sería interesante que otros usuarios reportasen si se encuentran o no con este fallo.

**Comment by Joshwani** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.worstestes, @libaice, @medied, @willcampbell433, @jimmyx0x, @dzxindex, @rkokhatskyi, @shx861, @LaContra, @Saqlaen, @naszam, @onenameneo, @0xdavinchee, @5pecia1, @dergroncki, @alfheimrShiven, @mudone, @PriyankaAngotra, @destomanu, @kblok
